theme: jekyll-theme-minimal

logo: https://avatars.githubusercontent.com/u/25256563?s=400&u=49c9861d19c2311aa00ba50fb090a05fb779f17c&v=4
title: David Douglas
description: 
   Computer Science M.S. "\n"\n
   
   San Diego State University "\n"\n
   
   Computer Science B.S. "\n"\n
   
   California State Polytechnic University, Pomona "\n"\n
   
