theme: jekyll-theme-minimal
kramdown:
  input: GFM
  hard_wrap: true
logo: https://avatars.githubusercontent.com/u/25256563?s=400&u=49c9861d19c2311aa00ba50fb090a05fb779f17c&v=4
title: David Douglas
description: |
   Computer Science M.S. \n
   San Diego State University
   Computer Science B.S.
   California State Polytechnic University, Pomona
   
